on: [push, pull_request]

name: Build test

jobs:
  build:
    name: Build test
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install AutoHotkey with Chocolatey
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install autohotkey
          # fix for [Unable to copy error by command line · Issue #68 · AutoHotkey/Ahk2Exe](https://github.com/AutoHotkey/Ahk2Exe/issues/68)
      - name: build
        shell: cmd
        run: ./build.bat
      - name: zip
        if: startsWith( github.ref, 'refs/tags/v' )
        shell: pwsh
        run:
          Compress-Archive -Path "vim_ahk"  -DestinationPath vim_ahk-${{github.ref_name}}.zip
      - name: Create Release
        if: startsWith( github.ref, 'refs/tags/v' )
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            vim_ahk-${{github.ref_name}}.zip
